# Generated by Django 4.1.5 on 2023-01-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testrun",
            name="environment",
            field=models.CharField(
                choices=[("D", "Development"), ("S", "Staging"), ("L", "Live")],
                default="D",
                max_length=1,
            ),
        ),
    ]
