# Generated by Django 4.1.5 on 2023-01-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_remove_section_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="testruncase",
            name="priority",
            field=models.CharField(
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                default="M",
                max_length=1,
            ),
        ),
    ]
