# Generated by Django 4.1.5 on 2023-01-11 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_testrun_environment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="section_hierachy",
        ),
        migrations.AlterField(
            model_name="testcase",
            name="case_id",
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name="testruncase",
            name="status",
            field=models.CharField(
                choices=[
                    ("U", "Untested"),
                    ("P", "Passed"),
                    ("F", "Failed"),
                    ("S", "Skipped"),
                    ("R", "Retest"),
                ],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AddConstraint(
            model_name="testruncase",
            constraint=models.UniqueConstraint(
                fields=("test_run", "test_case"), name="unique testcase for run"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="tests.section",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="section",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tests.section",
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("parent", "name"), name="unique section for parent"
            ),
        ),
    ]
